
<?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            // appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js")->
            appendFile($this->baseUrl() . "/js/modulos/login/login.js");
    ?>

<div class="row">
    <div class="col-md-10 col-md-offset-1">

        <h1>Usuarios</h1>
    </div><!-- //main content -->
</div><!-- //row -->