<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/reportes/clientes/gestionclientes.js"?>"></script>
<div>
<div class="panel-default"  align=center>
        <div class="row well" style="width:100%;">
            <h1>Reporte Gestión por Cliente</h1> 
        </div>
         <div class="panel-body "> <!-- seteamos los filtros -->
            <div class="col-lg-11 col-lg-offset-1">
                
                    <div class="form-group col-lg-5" >
                        <div class=" input-group">
                            <label>Cliente</label> 
                            <input id="cliente-reporte" type="text" name="selectInput" class="form-control input-sm " placeholder="">
                        </div>
                    </div>
                    <div class="form-group col-lg-2" >
                        <div class=" input-group">
                            <label>Fecha desde</label>
                            <input id="fechadesde-reporte" type="text" name="selectInput" class="form-control input-sm" placeholder="" >
                        </div>
                    </div>
                    <div class="form-group col-lg-2" >
                        <div class=" input-group">
                            <label>Fecha hasta</label>
                            <input id="fechahasta-reporte" type="text" name="selectInput" class="form-control input-sm" placeholder="" >
                        </div>
                    </div>   
                    <div class="form-group col-lg-3" >
                        <label class="col-lg-5 ">Resumen:</label>
                        <br>
                        <div class="col-lg-3">
                            <input id="resumen-reporte" type="checkbox" name="" value="S" onclick="muestraText()"> Si <br>
                        </div>
                    </div>                
            </div>
            <div class="col-lg-11 col-lg-offset-1">
                <textarea id="reporte-txt" rows="15" class="col-lg-10 col-lg-offset-1"></textarea>     
            </div>
        </div> <!-- row de filtros end -->
        <br>
        <div class="row "> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <!-- <a  id="cancelar-reporte"class="btn btn-danger">Cancelar</a> -->
                <a id="imprimir-reporte" class="btn btn-success">Imprimir</a>        
            </div>
        </div>
    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->
               
</div>