<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/suscripciones/suscripciones.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/suscripciones/gridSuscripciones.js"?>"></script>
  <style type="text/css" media="all">
    /* fix rtl for demo */
    .chosen-rtl .chosen-drop { left: -9000px; }
  </style>

<div>
<div class="panel-default " >
            <div class="row well" align=center>
                <h1>SUSCRIPCIONES</h1> 
            </div>
    <!-- <div class="panel-body "> -->
         <div class="row "  align=center> <!-- seteamos los filtros -->
            <div class="col-lg-11 col-lg-offset-1">
            
                <div class="form-group col-lg-3" >
                    <div class=" input-group">
                        Cliente
                        <input id="descripcionpersona-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder=" Nombre del cliente" >
                    </div>
                </div>
                 <div class="form-group col-lg-3">
                    <div class=" input-group">
                       Plan
                        <input id="planactivo-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder=" Plan">

                    </div>
                </div>
                <div class="form-group col-lg-3">
                    <div class=" input-group">
                       Vencimiento
                        <input id="fechavencimiento-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder=" Plan">

                    </div>
                </div>
              
                <div class="form-group col-lg-2">
                    <div class="input-group">
                        Estado
                        <select id="estadosuscripcion-filtro" class="input-sm form-control">
                            <option value="-1">Seleccione</option>
                         <option value="A">Activa</option>
                        <option value="N">Anulada</option>n>
                        </select>
                    </div>
                
                </div>
            
        </div> <!-- row de filtros end -->
        <br>
        <div class="row "  align=center> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <button type="button" class="btn btn-primary btn-sm" onclick="buscar()">
                    <i class="icon icon-search"></i> Buscar
                </button>
                <button type="button" class="btn btn-warning btn-sm " id="muestramodal"> <i
                    class="icon icon-eraser"></i> Nuevo
                </button>
            </div>
        </div>
        <br>
    
        <div class="row "> <!-- row para la tabla --> 
            <div class="col-lg-12" id="contenedorGrilla">
                <div class="table-responsive" >
                <table id="grillaSuscripciones"></table>
                <div id="paginadorSuscripciones"></div>
             </div>

            </div>
            
        </div>  <!-- end row tabla -->



    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->

    <div class="modal well" id="modalNuevo">   
        <div class="modal-content">
            <div class="modal-header">   
                <a class="close" id="close-modal">×</a>      
                <h1>SUSCRIPCION</h1>
            </div>               
            <div class="alert alert-danger" id="warning-modal" style="display: none;">
                    <div id="warning-message-modal"></div>
            </div>
            <div class="alert alert-success"  id="success-modal" style="display: none;">
                    <div id="success-message-modal"></div>
            </div> 
            <div class="modal-body">
                <div class="container"> 
                   
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Suscripción:</label>
                                <div class="col-lg-3">
                                    <input name="codigosuscripcion-modal" id="codigosuscripcion-modal" class="form-control input-sm"></input>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4"> 
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Fecha:</label>
                                <div class="col-lg-7">
                                    <input name="fechasuscripcion-modal" id="fechasuscripcion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>                           
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Cliente:</label>
                                <div class="col-lg-10">
                                    <select id="cliente-modal" class="" style="width: 100%;" onchange="">
                                    </select>
                                </div>
                            </div>
                        </div>
                            
                        <div class="col-lg-4"> 
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Vencimiento:</label>
                                <div class="col-lg-7">
                                    <input name="fechavencimiento-modal" id="fechavencimiento-modal" class="form-control input-sm"></input>
                                </div>
                            </div>                           
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Plan activo:</label>
                                <div class="col-lg-10">
                                    <select id="planactivo-modal" class="" style="width: 100%;"  onchange="calculaImporte()">
                                    </select>
                                    <!-- <input name="planactivo-modal" id="planactivo-modal" class="form-control input-sm"></input> -->
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Acreditación:</label>
                                <div class="col-lg-7">
                                    <input name="fechaacreditacion-modal" id="fechaacreditacion-modal" class="form-control input-sm"></input>
                                </div>
                               
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Importe gestión:</label>
                                <div class="col-lg-5">
                                    <input name="importegestion-modal" id="importegestion-modal" class="form-control input-sm"></input>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Estado:</label>
                                <div class="col-lg-7">
                                    <!-- <input name="cantidadgestion-modal" id="cantidadgestion-modal" class="form-control input-sm"></input> -->
                                    <select id="estadosuscripcion-modal" class="input-sm form-control">
                                        <option value="-1">Seleccione</option>
                                        <option value="A">Activa</option>
                                        <option value="N">Anulada</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    

                </div>
           </div>
        <div class="modal-footer">
            <a  id="cancelar-modal"class="btn btn-danger">Cancelar</a>
            <a id="guardar-modal" class="btn btn-success">Guardar</a>
        </div>
        </div>

                
    </div>
</div>
  <script type="text/javascript">
$(document).ready(function() { $("#cliente-modal").select2();
$("#asistenteservicios-modal").select2();
$("#planactivo-modal").select2(); });
  </script>




