<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/destinos/destinos.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/destinos/gridDestinos.js"?>"></script>
<div>
<div class="panel-default "   align=center>
            <div class="row well" style="width:100%;">
                <h1>DESTINOS</h1> 
            </div>
    <!-- <div class="panel-body "> -->
         <div class="row "> <!-- seteamos los filtros -->
            <div class="col-lg-11 col-lg-offset-1">
            
                <div class="form-group col-lg-5 col-lg-offset-3" >
                    <div class=" input-group col-lg-10">
                        
                        <input id="destino-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder="Destino" >
                    </div>
                </div>

             </div>
        </div> <!-- row de filtros end -->
        <br>
        <div class="row" > <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <button type="button" class="btn btn-primary btn-sm" onclick="buscar()">
                    <i class="icon icon-search"></i> Buscar
                </button>
                <button type="button" class="btn btn-warning btn-sm " id="muestramodal"> <i
                    class="icon icon-eraser"></i> Nuevo
                </button>
            </div>
        </div>
        <br>
    
        <div class="row "> <!-- row para la tabla --> 
            <div class="col-lg-12" id="contenedorGrilla">
                <div class="table-responsive" >
                <table id="grillaDestinos"></table>
                <div id="paginadorDestinos"></div>
             </div>

            </div>
            
        </div>  <!-- end row tabla -->



    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->
               
</div>

<div class="modal well" id="modalNuevo">   
    <div class="modal-content">
        <div class="modal-header">   
            <a class="close" id="close-modal">×</a>      
            <h1>DESTINOS</h1>
        </div>               
        <div class="alert alert-danger" id="warning-modal" style="display: none;">
                <div id="warning-message-modal"></div>
        </div>
        <div class="alert alert-success"  id="success-modal" style="display: none;">
                <div id="success-message-modal"></div>
        </div> 
        <div class="modal-body">
            <div class="container"  >
                <div class=" col-lg-8 col-lg-offset-2">  
                    
                    <div class="form-group col-lg-12">
                        <label class="col-lg-5 control-label">Cód. Destino</label>
                        <div class="col-lg-7">
                           <input id="codigodestino-modal" type="text" name="selectInput" 
                            class="form-control input-sm" disabled="disabled" required>
                        </div>
                     </div>

                      <div class="form-group col-lg-12">
                        <label class="col-lg-5 control-label">Descripcón</label>
                        <div class="col-lg-7">
                           <input id="descripcion-modal" type="text" 
                            class="form-control input-sm" required>
                        </div>
                     </div>

                     <div class="form-group col-lg-12">
                        <label class="col-lg-5 control-label">Zona</label>
                        <div class="col-lg-7">
                            <select id="zona-modal" style="width:100%";></select>
                        </div>
                     </div>
                     <div class="form-group col-lg-12">
                        <label class="col-lg-5 control-label">Ubicación</label>
                        <div class="col-lg-7">
                           <input id="ubicacion-modal" type="text" 
                            class="form-control input-sm"  required>
                        </div>
                     </div>
                </div>
           </div>
        </div>

        <div class="modal-footer">
            <a  id="cancelar-modal"class="btn btn-danger">Cancelar</a>
            <a id="guardar-modal" class="btn btn-success">Guardar</a>
        </div>
    </div>
</div>

