 <?php
    echo $this->headScript()->

            appendFile($this->baseUrl() ."/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() ."/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() ."/js/bootstrap.js")->
            appendFile($this->baseUrl() ."/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() ."/js/jquery.blockUI.js")->
            appendFile($this->baseUrl() ."/menu/js/modernizr.js")->
            appendFile($this->baseUrl() . '/menu/js/main.js')->
            appendFile($this->baseUrl() . '/js/modulos/layout/layout.js')->
            appendFile($this->baseUrl() ."/js/select2.js")->
            appendFile($this->baseUrl() ."/js/jquery.datetimepicker.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() ."/menu/css/reset.css")
            ->prependStylesheet($this->baseUrl() ."/menu/css/style.css")
            ->prependStylesheet($this->baseUrl() ."/css/style-min.css")
/*            ->prependStylesheet($this->baseUrl() ."/css/select2.css")
            ->prependStylesheet($this->baseUrl() ."/css/jquery.datetimepicker.css") */           
    ?>

<!doctype html>
<html lang="en" class="no-js">
<style>

.modal{
   /* margin-top: 0.5%;*/
    padding: 5% 5% 5%;
    background-color: #f7f7f7;
    -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
    -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
    box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
}

/* fix rtl for demo */
.chosen-rtl .chosen-drop { left: -9000px; }
.wrapColumnText { 
       white-space: normal !important; 
       height:auto; 
       vertical-align:text-top; 
}

</style>
<!--  <script type="text/javascript" src="funciones.js"></script> -->
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="<?php echo $this->baseUrl()."/menu/img/favicon.png"?>" type="image/x-icon" rel="shortcut icon" />
    <title>San Solución</title>
</head>
<body>
    <header>
        <a id="cd-logo" href="<?php echo $this->baseUrl()."/index.php/menu/menu"?>"><img src="<?php echo $this->baseUrl()."/menu/img/lurbana.png"?>" alt="Homepage"></a>
        <nav id="cd-top-nav">
            <ul>
<li><a  href="http://190.2.195.121/sansolucion/admin/index.php/maincontroller/records" target="_blank">Pedidos</a><span class="badge progress-bar-danger" id="pedidos"></span></li>
<li><a  href="<?php echo $this->baseUrl()."/index.php/administracion/perfilclientes"?>">Perfil</a></li>
<li><a  href="<?php echo $this->baseUrl()."/index.php/logistica/gestionescargas"?>">Nueva Gestión</a></li>
                <li><a  href="<?php echo $this->baseUrl()."/index.php/login/login"?>">Login</a></li>
            </ul>
        </nav>
        <a id="cd-menu-trigger" href="#0"><span class="cd-menu-text">Menu</span><span class="cd-menu-icon"></span></a>
    </header>
    <main class="cd-main-content">

        <!-- put your content here -->
        <!-- <div class="col-lg-12"> -->
            <?php
            echo $this->layout()->content;
            ?>
        <!-- </div> -->

    </main> <!-- cd-main-content -->

    <nav id="cd-lateral-nav">
        <ul class="cd-navigation">
            <li class="item-has-children">
                <a href="#0">Logistica</a>
                <ul class="sub-menu">
                    <li><a href="<?php echo $this->baseUrl()."/index.php/logistica/suscripciones"?>">Suscripciones</a></li>
                    <li><a href="<?php echo $this->baseUrl()."/index.php/logistica/planes"?>">Planes | Contratos</a></li>
                    <li><a href="<?php echo $this->baseUrl()."/index.php/logistica/gestiones"?>">Gestiones</a></li>
                    <li><a href="<?php echo $this->baseUrl()."/index.php/logistica/destinos"?>">Destinos</a></li>
                </ul>
            </li> <!-- item-has-children -->

            <li class="item-has-children">
                <a href="#0">Administración</a>
                <ul class="sub-menu">
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/administracion/clientes"?>">Clientes</a></li>
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/administracion/asistentes"?>">Asistentes de Servicios</a></li>
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/administracion/perfilclientes"?>">Perfil Clientes</a></li>
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/administracion/usuarios"?>">Usuarios</a></li>
                </ul>
            </li> <!-- item-has-children -->

            <li class="item-has-children">
                <a href="#0">Reportes</a>
                <ul class="sub-menu">
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/reportes/gestiongestor"?>">Gestión por gestor</a></li>
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/reportes/gestionclientes"?>">Gestión por cliente</a></li>
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/reportes/resumensaldosclientes"?>">Resumen consumo cliente</a></li>
                    <li><a  href="<?php echo $this->baseUrl()."/index.php/reportes/resumenconsumoasistentes"?>">Resumen Gestión Gestores</a></li>
                </ul>
            </li> <!-- item-has-children -->

            <li class="item-has-children">
                <a href="#0">Configuración</a>
                <ul class="sub-menu">
                    <li><a href="#0">Departamentos</a></li>
                    <li><a href="#0">Ciudades</a></li>
                    <li><a href="#0">Barrios</a></li>
                    <li><a href="#0"></a></li>
                </ul>
            </li> <!-- item-has-children -->
        </ul> <!-- cd-navigation -->
<!-- 
        <ul class="cd-navigation cd-single-item-wrapper">
            <li><a href="#0">Tour</a></li>
            <li><a href="#0">Login</a></li>
            <li><a href="#0">Register</a></li>
            <li><a href="#0">Pricing</a></li>
            <li><a href="#0">Support</a></li>
        </ul> 

        <ul class="cd-navigation cd-single-item-wrapper">
            <li><a class="current" href="#0">Journal</a></li>
            <li><a href="#0">FAQ</a></li>
            <li><a href="#0">Terms &amp; Conditions</a></li>
            <li><a href="#0">Careers</a></li>
            <li><a href="#0">Students</a></li>
        </ul> 

 -->
         <div class="cd-navigation socials">
            <a class="cd-twitter cd-img-replace" href="#0">Twitter</a>
            <a class="cd-github cd-img-replace" href="#0">Git Hub</a>
            <a class="cd-facebook cd-img-replace" href="#0">Facebook</a>
            <a class="cd-google cd-img-replace" href="#0">Google Plus</a>
        </div> <!-- socials
    </nav>
            
    
<!--    
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/main.js"></script>  Resource jQuery -->
</body>
</html>






