<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/gestiones.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/modalSuscripciones.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/gridGestiones.js"?>"></script>


<style type="text/css" media="all">
    /* fix rtl for demo */
    .chosen-rtl .chosen-drop { left: -9000px; }
    .wrapColumnText 
    { 
           white-space: normal !important; 
           height:auto; 
           vertical-align:text-top; 
    }  
</style>

<div>
<div class="panel-default "  align=center>
            <div class="row well" style="width:100%;">
                <h1>GESTIONES</h1> 
            </div>
    <!-- <div class="panel-body "> -->
         <div class="row "> <!-- seteamos los filtros -->
            <div class="col-lg-11 col-lg-offset-1">
            
                <div class="form-group col-lg-3" >
                    <div class=" input-group">
                        <!-- Cliente -->
                        <input id="cliente-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder=" Nombre del cliente" >
                    </div>
                </div>
                 <div class="form-group col-lg-3">
                    <div class=" input-group">
                       <!-- Documento cliente -->
                        <input id="documentocliente-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder=" Número de documento">

                    </div>
                </div>
              
                <div class="form-group col-lg-2">
                    <div class="input-group">
                        <!-- Estado -->
                        <select id="estadogestion-filtro" class="input-sm form-control">
                            <option value="-1">Estado</option>
                            <option value="P">Pendiente</option>
                            <option value="E">En Proceso</option>
                            <option value="F">Finalizado</option>
                            <option value="A">Anulado</option>
                        </select>
                    </div>
                
                </div>
             
                <div class="form-group col-lg-3">
                    <div class=" input-group">
                       <!-- Gestor -->
                        <input id="gestor-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder=" Gestor">
                    </div>
                </div>                

             </div>
        </div> <!-- row de filtros end -->
        <br>
        <div class="row "> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <button type="button" class="btn btn-primary btn-sm" onclick="buscar()">
                    <i class="icon icon-search"></i> Buscar
                </button>
                <button type="button" class="btn btn-warning btn-sm " id="muestramodal"> <i
                    class="icon icon-eraser"></i> Nuevo
                </button>
            </div>
        </div>
        <br>
    
        <div class="row" style="width:100%;"> <!-- row para la tabla --> 
            <div class="col-lg-12" id="contenedorGrilla">
                <div class="table-responsive" >
                <table id="grillaGestiones"></table>
                <div id="paginadorClientes"></div>
             </div>

            </div>
            
        </div>  <!-- end row tabla -->



    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->

    <div class="modal well" id="modalNuevo">   
        <div class="modal-content">
            <div class="modal-header">   
                <a class="close" id="close-modal">×</a>      
                <h1>Nueva gestión</h1>
            </div>               
            <div class="alert alert-danger" id="warning-modal" style="display: none;">
                    <div id="warning-message-modal"></div>
            </div>
            <div class="alert alert-success"  id="success-modal" style="display: none;">
                    <div id="success-message-modal"></div>
            </div> 
            <div class="modal-body">
                <div class="container"> 
                    <div class="row">

                        <div class="col-lg-8">
                            <div class="form-group col-lg-3 hide">
                                <!-- <label class="col-lg-6 control-label">Gestion:</label> -->
                                <div class="col-lg-12">
                                    <input name="codigogestion-modal" id="codigogestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Cliente:</label>
                                <div class="col-lg-7">
                                    <select id="cliente-modal" class="" style="width: 100%;">
                                    </select>
                                </div>
                                <div class="col-lg-3">
                                    <input name="tipocliente-modal" id="tipocliente-modal" class="form-control input-sm"></input>
                                    <input name="tipoclientecodigo-modal" id="tipoclientecodigo-modal" class="hide"></input>
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Fecha:</label>
                                <div class="col-lg-7">
                                    <input name="fechagestion-modal" id="fechagestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                        </div>
                    </div >
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Tarea:</label>
                                <div class="col-lg-10">
                                    <textarea class="form-control" id="tarea-modal" placeholder="Ingrese comentario" rows="6" maxlength="1500"> </textarea>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4"> 
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Inicio:</label>
                                <div class="col-lg-7">
                                    <input name="iniciogestion-modal" id="iniciogestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Fin:</label>
                                <div class="col-lg-7">
                                    <input name="fingestion-modal" id="fingestion-modal" class="form-control input-sm"></input>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Tiempo Estimado:</label>
                                <div class="col-lg-5">
                                    <input name="tiempoestimado-modal" type="number" id="tiempoestimado-modal" class="form-control input-sm"></input>
                                </div>
                                <div class="col-lg-2"> <span>min</span></div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Cant gestiones:</label>
                                <div class="col-lg-5">
                                    <input name="cantidadgestion-modal" type="" id="cantidadgestion-modal" class="form-control input-sm"></input>
                                </div>
                                <div class="col-lg-2"> <span>uni</span></div>
                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Asignado a:</label>
                                <div class="col-lg-10">
                                    <select id="asistenteservicios-modal"  class="" style="width:100%;">
                                     
                                    </select>
                                    <!-- <input name="gestor-modal" id="gestor-modal" class="form-control input-sm"></input> -->
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Estado:</label>
                                <div class="col-lg-7">
                                    <!-- <input name="cantidadgestion-modal" id="cantidadgestion-modal" class="form-control input-sm"></input> -->
                                    <select id="estado-modal" class="input-sm form-control">
                                        <option value="-1">Seleccione</option>
                                        <option value="P">Pendiente</option>
                                        <option value="E">En Proceso</option>
                                        <option value="F">Finalizado</option>
                                        <option value="A">Anulado</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Plan activo:</label>
                                <div class="col-lg-10">
                                    <ul class="list-group" id="planactivo-modal">
                                     </ul>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Saldo:</label>
                                <div class="col-lg-5">
                                    <input name="saldogestion-modal" id="saldogestion-modal" class="form-control input-sm"></input>
                                </div>
                                <div class="col-lg-2"> <span>uni</span></div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label"> Enviar email:</label>
                                <div class="col-lg-5">
                                    <input id="enviaremail-modal" type="checkbox" name="vehicle" value="SI" > Si<br>
                                </div>
                            </div>
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label"> Gentileza:</label>
                                <div class="col-lg-5">
                                    <input id="gentileza-modal" type="checkbox" name="" value="S" > Si<br>
                                </div>
                            </div>
                        </div>
                    </div>
                    

                </div>
           </div>
        <div class="modal-footer">
            <a  id="cancelar-modal"class="btn btn-danger">Cancelar</a>
            <a id="guardar-modal" class="btn btn-success">Guardar</a>
        </div>
        </div>

                
    </div>

    <div class="modal well" id="modalNuevo-suscripcion">   
        <div class="modal-content">
            <div class="modal-header">   
                <a class="close" id="close-modal-suscripcion">×</a>      
                <h1>SUSCRIPCION</h1>
            </div>               
            <div class="alert alert-danger" id="warning-modal-suscripcion" style="display: none;">
                    <div id="warning-message-modal-suscripcion"></div>
            </div>
            <div class="alert alert-success"  id="success-modal-suscripcion" style="display: none;">
                    <div id="success-message-modal-suscripcion"></div>
            </div> 
            <div class="modal-body">
                <div class="container"> 
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Suscripción:</label>
                                <div class="col-lg-3">
                                    <input name="codigosuscripcion-modal-suscripcion" id="codigosuscripcion-modal-suscripcion" class="form-control input-sm"></input>
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4"> 
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Fecha:</label>
                                <div class="col-lg-7">
                                    <input name="fechasuscripcion-modal-suscripcion" id="fechasuscripcion-modal-suscripcion" class="form-control input-sm"></input>
                                </div>
                            </div>                           
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Cliente:</label>
                                <div class="col-lg-10">
                                    <select id="cliente-modal-suscripcion" class="" style="width: 100%;" onchange="">
                                    </select>
                                </div>
                            </div>
                        </div>
                            
                        <div class="col-lg-4"> 
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Vencimiento:</label>
                                <div class="col-lg-7">
                                    <input name="fechavencimiento-modal-suscripcion" id="fechavencimiento-modal-suscripcion" class="form-control input-sm"></input>
                                </div>
                            </div>                           
                        </div>

                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Plan activo:</label>
                                <div class="col-lg-10">
                                    <select id="planactivo-modal-suscripcion" class="" style="width: 100%;"  onchange="calculaImporte()">
                                    </select>
                                    <!-- <input name="planactivo-modal" id="planactivo-modal" class="form-control input-sm"></input> -->
                                </div>
                                    
                            </div>
                        </div>
                        <div class="col-lg-4" id="divAcreditacion">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Acreditación:</label>
                                <div class="col-lg-7">
                                    <input name="fechaacreditacion-modal-suscripcion" id="fechaacreditacion-modal-suscripcion" class="form-control input-sm"></input>
                                </div>
                               
                            </div>
                        </div>
                         <div class="col-lg-4">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-5 control-label">Estado:</label>
                                <div class="col-lg-7">
                                    <!-- <input name="cantidadgestion-modal" id="cantidadgestion-modal" class="form-control input-sm"></input> -->
                                    <select id="estadosuscripcion-modal-suscripcion" class="input-sm form-control">
                                        <option value="-1">Seleccione</option>
                                        <option value="A">Activa</option>
                                        <option value="N">Anulada</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="form-group col-lg-12">
                                <label class="col-lg-2 control-label">Importe gestión:</label>
                                <div class="col-lg-5">
                                    <input name="importegestion-modal-suscripcion" id="importegestion-modal-suscripcion" class="form-control input-sm"></input>
                                </div>
                                    
                            </div>
                        </div>
                       
                    </div>
                    
                    

                </div>
           </div>
        <div class="modal-footer">
            <a  id="cancelar-modal-suscripcion"class="btn btn-danger">Cancelar</a>
            <a id="guardar-modal-suscripcion" class="btn btn-success">Guardar</a>
        </div>
        </div>

                
    </div>
    <div class="modal well" id="modalNuevo-track">   
    <div class="modal-content">
        <div class="modal-header">   
            <a class="close" id="close-modal-track">×</a>      
            <h1>Track</h1>
        </div>               
        <div class="alert alert-danger" id="warning-modal-track" style="display: none;">
                <div id="warning-message-modal-track"></div>
        </div>
        <div class="alert alert-success"  id="success-modal-track" style="display: none;">
                <div id="success-message-modal-track"></div>
        </div> 
        <div class="modal-body" style="overflow:hidden">
            <div class="container">
                <div class="row">
                    <div class="col-lg-1 hide">
                        <input name="gestion-track" id="gestion-track" class="form-control input-sm" placeholder="gestion"></input>
                    </div>  
                    <div class="col-lg-1 hide">
                        <input name="orden-track" id="orden-track" class="form-control input-sm" placeholder="orden"></input>
                    </div>  
                    <div class="col-lg-1">
                        <input name="proceso-track" id="proceso-track" class="form-control input-sm" placeholder="Paso"></input>
                    </div>    
                    <div class="col-lg-2">
                      <select id="zona-track" class="input-sm form-control" placeholder="Zonas">
                      </select>
                    </div>
                    <div class="col-lg-4">
                        <input name="descripcion-track" id="descripcion-track" class="form-control input-sm" placeholder="Actividad"></input>
                    </div>
                    <div class="col-lg-2" placeholder="Estado">
                      <select id="realizado-track" class="input-sm form-control">
                        <option value="-1">Realizado?</option>
                        <option value="1">Si</option>
                        <option value="0">No</option>
                      </select>
                    </div>
                    <div class="col-lg-2">
                        <input name="hora-track" id="hora-track" class="form-control input-sm" type="text"></input>
                    </div>
                    <div class="col-lg-1">
                        <a  id="add-track"class="btn btn-success" ><i class="icon icon-save"></i></a>
                    </div>
                </div>
            </div>
            <BR>
            <div class="container"> 
               <div class="table-responsive" >
                   <table id="grillaGestionesTrack"></table>
                </div>
           </div>
       </div>
        <div class="modal-footer">
            <a  id="cancelar-modal-track"class="btn btn-danger">Cancelar</a>
        </div>
    </div>       
</div>
</div>
  <script type="text/javascript">
$(document).ready(function() { 
$("#hora-track").datetimepicker();
$("#cliente-modal").select2();
$("#asistenteservicios-modal").select2();
$("#cliente-modal-suscripcion").select2();
$("#asistenteservicios-modal-suscripcion").select2();
$("#planactivo-modal-suscripcion").select2(); 
});

  </script>




