
<?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            // appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js")->
            appendFile($this->baseUrl() . "/js/modulos/login/login.js");
    ?>
<style>

    .modal{
       /* margin-top: 0.5%;*/
        padding: 5% 10% 10%;
        background-color: #f7f7f7;
        -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
        -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
    }

</style>
<div class="row">
    <div class="col-md-10 col-md-offset-1">

        <h1>Usuarios</h1>
    </div><!-- //main content -->
</div><!-- //row -->