<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/gestionescargas.js "?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/modalSuscripciones.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/gestiones/gridGestionescargas.js "?>"></script>
<style type="text/css" media="all">
   html {
   overflow-y:scroll;
   }
   /* fix rtl for demo */
   .chosen-rtl .chosen-drop {
   left: -9000px;
   }
   .wrapColumnText {
   white-space: normal !important;
   height: auto;
   vertical-align: text-top;
   }
</style>
<div>
   <div class="panel-default">
      <div class="col-lg-12 ">
         <div class="panel panel-primary">
            <div class="panel-heading" data-toggle="collapse" data-parent="#datosPersonales" href="#collapseDatosPersonales">
               <h3 class="panel-title"><a > Datos Generales</a></h3>
            </div>
            <div id="collapseDatosPersonales" class="panel-collapse">
               <div class="panel-body">
                <div class="alert alert-danger" id="warning-modal" style="display: none;">
                  <div id="warning-message-modal"></div>
               </div>
               <div class="alert alert-success"  id="success-modal" style="display: none;">
                  <div id="success-message-modal"></div>
               </div>
                  <div class="row">
                     <div class="col-lg-8">
                        <div class="form-group col-lg-3 hide">
                           <!-- <label class="col-lg-6 control-label">Gestion:</label> -->
                           <div class="col-lg-12">
                              <input name="codigogestion-modal" id="codigogestion-modal" class="form-control input-sm">
                           </div>
                        </div>
                        <div class="form-group col-lg-12">
                           <label class="col-lg-2 control-label">Cliente:</label>
                           <div class="col-lg-7">
                              <select id="cliente-modal" class="" style="width: 100%;">
                              </select>
                           </div>
                           <div class="col-lg-3">
                              <input name="tipocliente-modal" id="tipocliente-modal" class="form-control input-sm">
                              <input name="tipoclientecodigo-modal" id="tipoclientecodigo-modal" class="hide">
                           </div>
                        </div>
                        <div class="form-group col-lg-12">
                           <label class="col-lg-2 control-label">Tarea:</label>
                           <div class="col-lg-10">
                              <textarea class="form-control" id="tarea-modal" placeholder="Ingrese comentario" rows="2" maxlength="1500"> </textarea>
                           </div>
                        </div>
                        <div class="form-group col-lg-12">
                           <label class="col-lg-2 control-label">Asignado a:</label>
                           <div class="col-lg-10">
                              <select id="asistenteservicios-modal"  class="" style="width:100%;">
                              </select>
                           </div>
                        </div>
                        <div class="form-group col-lg-12">
                           <label class="col-lg-2 control-label">Plan activo:</label>
                           <div class="col-lg-10">
                              <ul class="list-group" id="planactivo-modal">
                              </ul>
                           </div>
                        </div>
                     </div>
                     <div class="col-lg-4">
                           <div class="form-group col-lg-12">
                              <label class="col-lg-3 control-label">Fecha:</label>
                              <div class="col-lg-7">
                                 <input name="fechagestion-modal" id="fechagestion-modal" class="form-control input-sm">
                              </div>
                           </div>
                         <div class="form-group col-lg-12 hide">
                           <label class="col-lg-3 control-label">Inicio:</label>
                           <div class="col-lg-9">
                              <input name="iniciogestion-modal" id="iniciogestion-modal" class="form-control input-sm">
                           </div>
                        </div>
                        <div class="form-group col-lg-12 hide">
                           <label class="col-lg-3 control-label">Fin:</label>
                           <div class="col-lg-9">
                              <input name="fingestion-modal" id="fingestion-modal" class="form-control input-sm">
                           </div>
                        </div> 
                        <div class="form-group col-lg-12">
                           <label class="col-lg-3 control-label">Tiempo Estimado:</label>
                           <div class="col-lg-7">
                              <input name="tiempoestimado-modal" type="number" id="tiempoestimado-modal" class="form-control input-sm">
                           </div>
                           <div class="col-lg-2"> <span>min</span>
                           </div>
                        </div>
                        <div class="form-group col-lg-12">
                           <label class="col-lg-3 control-label">Cant gestiones:</label>
                           <div class="col-lg-7">
                              <input name="cantidadgestion-modal" type="" id="cantidadgestion-modal" class="form-control input-sm">
                           </div>
                           <div class="col-lg-2"> <span>uni</span>
                           </div>
                        </div>
                        <div class="form-group col-lg-12">
                           <label class="col-lg-3 control-label">Saldo:</label>
                           <div class="col-lg-7">
                              <input name="saldogestion-modal" id="saldogestion-modal" class="form-control input-sm">
                           </div>
                           <div class="col-lg-2">
                              <span>uni</span>
                           </div>
                        </div>
                        <div class="col-lg-12">
                              <label class="col-lg-3 control-label"> Email:</label>
                              <div class="col-lg-3">
                                 <input id="enviaremail-modal" type="checkbox" name="vehicle" value="SI"> Si
                              </div>
                              <label class="col-lg-4 control-label"> Gentileza:</label>
                              <div class="col-lg-2">
                                 <input id="gentileza-modal" type="checkbox" name="" value="S"> Si
                              </div>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="col-lg-12 ">
         <div class="panel panel-primary">
            <div class="panel-heading" data-toggle="collapse" data-parent="#collapseDetalles" href="#collapseDetalles">
               <h3 class="panel-title"><a > Detalles Actividades</a></h3>
            </div>
            <div id="collapseDetalles" class="panel-collapse collapse">
               <div class="panel-body">
                  <div class="row">
                     <div class="alert alert-danger" id="warning-modal-acti" style="display: none;">
                        <div id="warning-message-modal-acti"></div>
                     </div>
                     <div class="alert alert-success"  id="success-modal-acti" style="display: none;">
                        <div id="success-message-modal-acti"></div>
                     </div>
                        <div class="container">
                          
                              <button type="button" class="btn btn-warning btn-sm " id="mostrar-modal-actividad"> <i class="icon icon-eraser"></i> Nueva Actividad</button>
                           <br> 
                           <br>  
                              
                           <div class="table-responsive" id="grid">
                              <table id="grillaGestionesTrack"></table>
                           </div>
                           <div class="table-responsive" id="form">
                              <div class="panel panel-default">
                              <div class="panel-heading">Nueva Actividad <a class="close" id="close-modal">×</a></div>

                                <div class="panel-body">
                                   <div class="row col-lg-8 col-lg-offset-2">
                                 <div class="form-group col-lg-12 hidden">
                                    <div class="hidden">
                                       <input name="modificar-acti" type="text" id="modificar-acti" class="form-control input-sm "> 
                                       <input name="motivo-cancel-acti" type="text" id="motivo-cancel-acti" class="form-control input-sm "> 
                                       <input name="sync-acti" type="text" id="sync-acti" class="form-control input-sm "> 
                                       <input name="latitud-acti" type="text" id="latitud-acti" class="form-control input-sm "> 
                                       <input name="longitud-acti" type="text" id="longitud-acti" class="form-control input-sm "> 
                                       <input name="inicio-actividad-acti" type="text" id="inicio-actividad-acti" class="form-control input-sm ">
                                       <input name="fin-actividad-acti" type="text" id="fin-actividad-acti" class="form-control input-sm ">
                                    </div>
                                    <label class="col-lg-2 control-label ">Gestión</label>
                                    <div class="col-lg-4">
                                       <input name="codigo-gestion-acti" type="text" id="codigo-gestion-acti" class="form-control input-sm">
                                    </div> 
                                    <label class="col-lg-2 control-label">Orden</label>
                                    <div class="col-lg-4">
                                       <input name="orden-acti" type="text" id="orden-acti" class="form-control input-sm">
                                    </div>
                                 </div>
                                 <div class="form-group col-lg-12">
                                    <label class="col-lg-2 control-label">Paso</label>
                                    <div class="col-lg-4">
                                       <input name="proceso-acti" type="number" id="proceso-acti" class="form-control input-sm">
                                    </div> 
                                    <label class="col-lg-2 control-label">Realizado</label>
                                    <div class="col-lg-4">
                                        <select id="realizado-acti"  class="" style="width:100%;">
                                          <option value="0">No</option>
                                          <option value="1">Si</option>    
                                       </select>
                                    </div>
                                 </div>
                                 <div class="form-group col-lg-12 hidden">
                                    <label class="col-lg-2 control-label">Asistente</label>
                                    <div class="col-lg-10">
                                       <select id="asistente-acti"  class="" style="width:100%;">
                                       </select>
                                    </div>
                                 </div>
                                 <div class="form-group col-lg-12">
                                    <label class="col-lg-2 control-label">Zona</label>
                                    <div class="col-lg-10">
                                        <select id="zona-acti" style="width:100%";></select>
                                    </div>
                                 </div>
                                 <div class="form-group col-lg-12">
                                    <label class="col-lg-2 control-label">Destino</label>
                                    <div class="col-lg-6">
                                        <input name="destino-acti" type="text" id="destino-acti" class="form-control input-sm">
                                    </div> 
                                    <label class="col-lg-1 control-label">Hora</label>
                                    <div class="col-lg-3">
                                        <input name="hora-estimada-acti" id="hora-estimada-acti" class="form-control input-sm">
                                    </div>
                                 </div>
                                 <div class="form-group col-lg-12">
                                    <label class="col-lg-2 control-label">Descripción</label>
                                    <div class="col-lg-10">
                                        <textarea class="form-control" id="descripcion-acti" placeholder="Ingrese comentario" rows="2" maxlength="599"> </textarea>
                                    </div>
                                 </div>
                                 <div class="form-group col-lg-12">
                                    <label class="col-lg-2 control-label">Fecha</label>
                                    <div class="col-lg-4">
                                        <input name="hora-acti" id="hora-acti" class="form-control input-sm" >
                                    </div>

                                    <div class="col-lg-6 ">
                                       <div class="col-lg-2 col-lg-offset-8">
                                           <a  id="cancel-actividad"class="btn btn-danger" ><i class="icon icon-undo"></i></a>
                                       </div>
                                       <div class="col-lg-2">
                                           <a  id="add-actividad"class="btn btn-success" ><i class="icon icon-save"></i></a>
                                       </div>
                                       
                                       
                                    </div>
                                 </div>
                                
                              </div>
                                </div>
                              </div>
                              

                             <!-- codigo_gestion+orden es pk
                             codigo_gestor
                             codigo_zona(tabla zona)
                             descripcion(que hacer, texto)
                             destino(donde se va, texto)
                             realizado(por defecto no osea 0)
                             paso-proceso(el orden de ejecucion de las actividades)
                             fecha_hora(mostrar no cargar) -->

                           </div>
                           </div>
                           
                        </div>

                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="modal-footer">
      <a  id="cancelar-modal"class="btn btn-danger">Cancelar</a>
      <a id="guardar-modal" class="btn btn-success">Guardar</a>
   </div>
</div>
<div class="modal well" id="modalNuevo-suscripcion">
   <div class="modal-content">
      <div class="modal-header">
         <a class="close" id="close-modal-suscripcion">×</a>      
         <h1>SUSCRIPCION</h1>
      </div>
      <div class="alert alert-danger" id="warning-modal-suscripcion" style="display: none;">
         <div id="warning-message-modal-suscripcion"></div>
      </div>
      <div class="alert alert-success"  id="success-modal-suscripcion" style="display: none;">
         <div id="success-message-modal-suscripcion"></div>
      </div>
      <div class="modal-body">
         <div class="container">
            <div class="row">
               <div class="col-lg-8">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-2 control-label">Suscripción:</label>
                     <div class="col-lg-3">
                        <input name="codigosuscripcion-modal-suscripcion" id="codigosuscripcion-modal-suscripcion" class="form-control input-sm">
                     </div>
                  </div>
               </div>
               <div class="col-lg-4">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-5 control-label">Fecha:</label>
                     <div class="col-lg-7">
                        <input name="fechasuscripcion-modal-suscripcion" id="fechasuscripcion-modal-suscripcion" class="form-control input-sm">
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-8">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-2 control-label">Cliente:</label>
                     <div class="col-lg-10">
                        <select id="cliente-modal-suscripcion" class="" style="width: 100%;" onchange="">
                        </select>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-5 control-label">Vencimiento:</label>
                     <div class="col-lg-7">
                        <input name="fechavencimiento-modal-suscripcion" id="fechavencimiento-modal-suscripcion" class="form-control input-sm">
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-8">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-2 control-label">Plan activo:</label>
                     <div class="col-lg-10">
                        <select id="planactivo-modal-suscripcion" class="" style="width: 100%;"  onchange="calculaImporte()">
                        </select>
                     </div>
                  </div>
               </div>
               <div class="col-lg-4" id="divAcreditacion">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-5 control-label">Acreditación:</label>
                     <div class="col-lg-7">
                        <input name="fechaacreditacion-modal-suscripcion" id="fechaacreditacion-modal-suscripcion" class="form-control input-sm">
                     </div>
                  </div>
               </div>
               <div class="col-lg-8">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-2 control-label">Estado:</label>
                     <div class="col-lg-10">
                        <select id="estadosuscripcion-modal-suscripcion" class="form-control input-sm">
                           <option value="-1">Seleccione</option>
                           <option value="A">Activa</option>
                           <option value="N">Anulada</option>
                        </select>
                     </div>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-lg-8">
                  <div class="form-group col-lg-12">
                     <label class="col-lg-2 control-label">Importe gestión:</label>
                     <div class="col-lg-5">
                        <input name="importegestion-modal-suscripcion" id="importegestion-modal-suscripcion" class="form-control input-sm">
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <div class="modal-footer">
         <a  id="cancelar-modal-suscripcion"class="btn btn-danger">Cancelar</a>
         <a id="guardar-modal-suscripcion" class="btn btn-success">Guardar</a>
      </div>
   </div>
</div>
<script type="text/javascript">
   $(document).ready(function() {
   
       $("#hora-acti").datetimepicker();
        $("#hora-estimada-acti").datetimepicker({
             datepicker:false,
             format:'H:i'
         });
       $("#cliente-modal").select2();
       $("#asistenteservicios-modal").select2();
       $("#asistente-acti").select2();
       $("#zona-acti").select2();
       $("#realizado-acti").select2();
       $("#cliente-modal-suscripcion").select2();
       $("#asistenteservicios-modal-suscripcion").select2();
       $("#planactivo-modal-suscripcion").select2();
       document.getElementById("modalNuevo-suscripcion").style.paddingTop = "70px";
       //$("#modalNuevo-suscripcion").show();
       cargarModalNuevo();
       var param = new Object();
       param.NUMERO_GESTION = 1112;
       track(param);
      
   
   });
</script>