<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
 <?php
    echo $this->headScript()->

			appendFile($this->baseUrl() . "/menu/js/modernizr.js")->
			// appendFile($this->baseUrl() . "/js/jquery.min.js")->
            // appendFile($this->baseUrl() . "/js/bootstrap.js")->
            // /appendFile($this->baseUrl() . "/js/bootstrap.min.js")->
			// appendFile($this->baseUrl() . "/js/jquery.jqgrid.min.js")->
			// appendFile($this->baseUrl() . '/js/grid.locale-es.js')->
   //          appendFile($this->baseUrl() . '/js/jquery-ui-1.9.2.custom.min.js')->
			// appendFile($this->baseUrl() . '/js/jjquery-1.7.1.js')->
			appendFile($this->baseUrl() . '/menu/js/main.js')->
			appendFile($this->baseUrl() . "/js/blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
			->prependStylesheet($this->baseUrl() . "/menu/css/reset.css")
			->prependStylesheet($this->baseUrl() . "/menu/css/style.css")
			->prependStylesheet($this->baseUrl() . "/css/style.css")
    ?>

<!doctype html>
<html lang="en" class="no-js">
<style>

    .tarjeta{
        margin-top: 30px;
        padding: 15px 10px 15px;
        background-color: #f7f7f7;
        -moz-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
        -webkit-box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.5);
    }

    .logo-usuario{
        width: 159px;
        height: 96px;
        margin: 0 auto 20px;
        display: block;
        -moz-border-radius: 1%;
        -webkit-border-radius: 1%;
        border-radius: 1%;
    }

</style>
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<!--	<link href='http://fonts.googleapis.com/css?family=Titillium+Web:400,600,700' rel='stylesheet' type='text/css'> -->

	<!--<link rel="stylesheet" href="css/reset.css">  CSS reset -->
	<!--<link rel="stylesheet" href="css/style.css">  Resource style -->
	<!-- <script src="js/modernizr.js"></script>  Modernizr -->
  	
	<title>Logistic</title>
</head>
<body>
	<header>
		<a id="cd-logo" href="#0"><img src="<?php echo $this->baseUrl(). "/menu/img/lurbana.png"?>" alt="Homepage"></a>
	
	</header>
	<main class="cd-main-content">

		<!-- put your content here -->
		<div class="col-lg-12">
            <?php
            echo $this->layout()->content;
            ?>
        </div>

	</main> <!-- cd-main-content -->
</body>
</html>






