<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/administracion/perfilclientes/perfilclientes.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/administracion/perfilclientes/gridPerfilclientes.js"?>"></script>
<div>
    <br>
<div class="col-lg-12">
            <div class="row" id="filtros">
                <div class="col-lg-4">
                    <div class="input-group" >
                      <span class="input-group-addon" id="basic-addon1">Nombre</span>
                      <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Buscar!</button>
                      </span>
                    </div>
                </div>
               
                <div class="col-lg-4">
                    <div class="input-group">
                      <span class="input-group-addon" id="basic-addon1">Ruc</span>
                      <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
                      <span class="input-group-btn">
                        <button class="btn btn-default" type="button">Buscar!</button>
                      </span>
                    </div>
                </div>                
            </div>
             <br>
            <div class="row" id="informacionCliente">
                <div class="col-lg-6">
                    <div class="panel panel-primary">
                      <div class="panel-heading">
                        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#datosPersonales" href="#collapseDatosPersonales"> Datos Personales</a></h3>
                      </div>
                          <div id="collapseDatosPersonales" class="panel-collapse collapse">
                              <div class="panel-body">
                                <div class="form-group col-lg-12">
                                  <label class="control-label col-lg-2"> Cliente</label>
                                  <div class="col-lg-9">
                                    <input type="text" id="cliente-info" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-12">
                                  <label class="control-label col-lg-2"> Tipo Cliente</label>
                                  <div class="col-lg-9">
                                    <input type="text" id="tipocliente-info" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-4"> Documento</label>
                                  <div class="col-lg-8">
                                    <input type="text" id="documentocliente-info" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-4"> Telefono</label>
                                  <div class="col-lg-8">
                                    <input type="text" id="telefonocliente-info" class="form-control input-sm" placeholder="">
                                  </div>
                                </div>
                                <div class="form-group col-lg-12">
                                  <label class="control-label col-lg-2"> Dirección</label>
                                  <div class="col-lg-9">
                                    <input type="text" id="direccioncliente-info" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                 
                                
                               
                              </div>
                          </div>
                    </div>
                </div>
                <div class="col-lg-6">
                   <div class="panel panel-primary">
                      <div class="panel-heading">
                        <h3 class="panel-title"><a data-toggle="collapse" data-parent="#informacionSaldos" href="#collapseInformacionSaldos"> Saldos </a></h3>
                      </div>
                          <div id="collapseInformacionSaldos" class="panel-collapse collapse">
                              <div class="panel-body">
                                <div class="form-group col-lg-12">
                                  <label class="control-label col-lg-3">Saldos: </label>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Suscripción Mensual Actual: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Suscripción Mensual Anterior: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Suscripción Casual Actual: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div>
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Suscripción Casual Anterior: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 

                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Cantidad Gestiones Utilizadas en el Mes: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Cantidad Gestiones Eventuales Utilizadas en el Mes: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div>  
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-9">Total Gestiones Disponibles: </label>
                                  <div class="col-lg-3">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                <div class="form-group col-lg-6">
                                  <label class="control-label col-lg-5">Total a Abonar: </label>
                                  <div class="col-lg-7">
                                    <input type="text" class="form-control input-sm" placeholder="">
                                  </div>
                                </div> 
                                
                                
                               
                              </div>
                          </div>
                    </div>
                </div>
            </div>
            <div class="row" id="ultimasGestiones">
                <div class="col-lg-12">
                     <div class="panel panel-primary">
                      <div class="panel-heading">
                        <h3 class="panel-title">Ultimas Gestiones</h3>
                      </div>
                      <div class="panel-body">
                       <div class="table-responsive">
                                <table class="table table-striped table-bordered table-hover">
                                    <thead>
                                        <tr>
                                            <th>#</th>
                                            <th>First Name</th>
                                            <th>Last Name</th>
                                            <th>Username</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td>1</td>
                                            <td>Mark</td>
                                            <td>Otto</td>
                                            <td>@mdo</td>
                                        </tr>
                                        <tr>
                                            <td>2</td>
                                            <td>Jacob</td>
                                            <td>Thornton</td>
                                            <td>@fat</td>
                                        </tr>
                                        <tr>
                                            <td>3</td>
                                            <td>Larry</td>
                                            <td>the Bird</td>
                                            <td>@twitter</td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                      </div>
                    </div>
                </div>
               <!--  <div class="col-lg-6">

                </div> -->

            </div>
</div> <!-- end panel default -->

<script type="text/javascript">
$(document).ready(function() { 

  </script>