<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/reportes/asistentes/resumenconsumoasistentes.js"?>"></script>
<div>
<div class="panel-default"  align=center>
        <div class="row well">
            <h1>Reporte Resumen Gestiones Gestores</h1> 
        </div>
         <div class="panel-body "> <!-- seteamos los filtros -->
            <div class="col-lg-11 col-lg-offset-1">
                
                    <div class="form-group col-lg-4" >
                        <div class=" input-group">
                            <label>Gestor</label> 
                            <input id="gestor-reporte" type="text" name="selectInput" class="form-control input-sm col-lg-11" placeholder="">
                        </div>
                    </div>
                    <div class="form-group col-lg-2" >
                        <div class=" input-group">
                            <label>Mes</label>
                            <select id="mes-reporte" class="form-control input-sm" > 
                             <option value="0"></option>
                             <option value="1">Enero</option>
                             <option value="2">Febrero</option>
                             <option value="3">Marzo</option>
                             <option value="4">Abril</option>
                             <option value="5">Mayo</option>
                             <option value="6">Junio</option>
                             <option value="7">Julio</option>
                             <option value="8">Agosto</option>
                             <option value="9">Setiembre</option>
                             <option value="10">Octubre</option>
                             <option value="11">Noviembre</option>
                            <option value="12">Diciembre</option></select>
                        </div>
                    </div>
                    <div class="form-group col-lg-2" >
                        <div class=" input-group">
                            <label>Año</label>
                            <select id="ano-reporte" class="form-control input-sm" placeholder="" ></select>
                        </div>
                    </div>

                    <div class="form-group col-lg-3" style="visibility: hidden;">
                        <label class="col-lg-5 "> Gentileza:</label>
                        <br>
                        <div class="col-lg-3">
                            <input id="gentileza-reporte" type="checkbox" name="" value="S" disabled> Si <br>
                        </div>
                    </div>
        </div> <!-- row de filtros end -->
        <br>
        <div class="row "> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <!-- <a  id="cancelar-reporte"class="btn btn-danger">Cancelar</a> -->
                <a id="imprimir-reporte" class="btn btn-success">Imprimir</a>        
            </div>
        </div>
        <br>
        <div class="row "> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <textarea id="reporte-txt" rows="15" class="col-lg-10 col-lg-offset-1"></textarea>     
            </div>
        </div>
    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->
               
</div>