<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/planes/planes.js"?>"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl() ."/js/modulos/logistica/planes/gridPlanes.js"?>"></script>
<div>
<div class="panel-default "  align=center>
            <div class="row well">
                <h1>PLANES</h1> 
            </div>
    <!-- <div class="panel-body "> -->
         <div class="row "> <!-- seteamos los filtros -->
            <div class="col-lg-11 col-lg-offset-1">
            
                <div class="form-group col-lg-6 col-lg-offset-2" >
                    <div class=" input-group col-lg-10">
                        Plan
                        <input id="descripcionplan-filtro" type="text" name="selectInput" class="form-control input-sm" placeholder="Plan" >
                    </div>
                </div>

             </div>
        </div> <!-- row de filtros end -->
        <br>
        <div class="row "> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-12">
                <button type="button" class="btn btn-primary btn-sm" onclick="buscar()">
                    <i class="icon icon-search"></i> Buscar
                </button>
                <button type="button" class="btn btn-warning btn-sm " id="muestramodal"> <i
                    class="icon icon-eraser"></i> Nuevo
                </button>
            </div>
        </div>
        <br>
    
        <div class="row "> <!-- row para la tabla --> 
            <div class="col-lg-12" id="contenedorGrilla">
                <div class="table-responsive" >
                <table id="grillaPlanes"></table>
                <div id="paginadorPlanes"></div>
             </div>

            </div>
            
        </div>  <!-- end row tabla -->



    <!-- </div>    end   panel body -->
</div> <!-- end panel default -->
               
</div>

<div class="modal well" id="modalNuevo">   
    <div class="modal-content">
        <div class="modal-header">   
            <a class="close" id="close-modal">×</a>      
            <h1>PLANES</h1>
        </div>               
        <div class="alert alert-danger" id="warning-modal" style="display: none;">
                <div id="warning-message-modal"></div>
        </div>
        <div class="alert alert-success"  id="success-modal" style="display: none;">
                <div id="success-message-modal"></div>
        </div> 
        <div class="modal-body">
            <div class="container"  >
                <div class=" col-lg-8 col-lg-offset-3">  
                    <div class="form-group " >
                        <div class=" input-group">
                            Código plan
                            <input id="codigoplan-modal" type="text" name="selectInput" class="form-control input-sm " placeholder=" " disabled="disabled" required>
                        </div>
                    </div>
                    
                   
                   
                     <div class="form-group" >
                        <div class=" input-group col-lg-8">
                            Nombre del Plan
                            <input id="descripcionplan-modal" type="text" name="selectInput" class="form-control input-sm" placeholder=" Nombre del plan" >
                        </div>
                    </div>
                    <div class="form-group" >
                        <div class=" input-group">
                            Tipo plan
                            <select id="tipoplan-modal" class="input-sm form-control">
                            <option value="-1">Seleccione</option>
                            <option value="M">Mensual</option>
                            <option value="C">Casual</option>
                        </select>
                        </div>
                    </div>
                     <div class="form-group" >
                        <div class=" input-group">
                            Cantidad
                            <input id="cantidadplan-modal" type="text" name="selectInput" class="form-control input-sm" placeholder=" Cantidad" >
                        </div>
                    </div>
                    <div class="form-group" >
                        <div class=" input-group">
                            Costo
                            <input id="costoplan-modal" type="text" name="selectInput" class="form-control input-sm" placeholder=" Costo" >
                        </div>
                    </div>  
                    
                     <div class="form-group" >
                        <div class=" input-group">
                            Estado
                            <select id="estadoplan-modal" class="input-sm form-control">
                            <option value="A">Activo</option>
                            <option value="I">Inactivo</option>
                        </select>
                        </div>
                    </div>

               </div>
           </div>
        </div>

        <div class="modal-footer">
            <a  id="cancelar-modal"class="btn btn-danger">Cancelar</a>
            <a id="guardar-modal" class="btn btn-success">Guardar</a>
        </div>
    </div>
</div>

