
<?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            // appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js")->
            appendFile($this->baseUrl() . "/js/modulos/login/login.js");
    ?>
<section xmlns="http://www.w3.org/1999/html">
<div class="panel-default">
    <div class="panel-heading">CLIENTES</div>
    <div class="panel-body well">
         <div class="row "> <!-- seteamos los filtros -->
            <form class="form-horizontal">
                <!-- Nro Solicitud - Autogenerado -->
                <div class="form-group col-lg-3" >
                    <label class="col-lg-5 control-label">Nro. Solicitud</label>
                    <div class="col-lg-7 input-group">
                        <input type="text" name="selectInput" class="form-control input-sm" placeholder="Número de solicitud" >
                    </div>
                </div>
                <!-- Tipo de Solicitud, busqueda remota -->
                <div class="form-group col-lg-3">
                    <label class="col-lg-4 control-label">Tipo</label>
                    <div class="col-lg-8 input-group">
                        <select class="input-sm form-control">
                            <option value="">-- Seleccionar --</option>
                        </select>
                    </div>
                
                </div>
                <!-- Nro Linea - Carga el usuario -->
                <div class="form-group col-lg-3">
                    <label class="col-lg-3 control-label">Nro. Línea</label>
                    <div class="col-lg-9 input-group">
                        <input type="text" ng-model="datos.linea" name="selectInput" class="form-control input-sm"
                               placeholder="Número de línea"
                               ng-blur="busquedaPorNroLinea()"
                               ng-disabled="lineaDisabled"
                               >
                    </div>
                </div>
                <!-- Grupo de facturacion, se carga el primero por defecto, luego el usuario selecciona-->
                <div class="form-group col-lg-3">
                    <label class="col-lg-7 control-label">Grupo de facturación</label>
                    <div class="col-lg-5 input-group">
                        <input type="text" ng-model="datos.codGrupFact" name="selectInput" class="form-control input-sm" placeholder="Grupo de facturación" ng-disabled="gruFacDisabled"
                        ng-blur="busquedaPorGruFact()">
                    </div>
                </div>
            </form>
        </div> <!-- row de filtros end -->
        <div class="row "> <!-- row de botones buscar, nuevo -->
            <div class="col-lg-8 col-lg-offset-2 ">
                <button type="button" class="btn btn-primary btn-sm">
                    <i class="icon icon-search"></i> Buscar
                </button>
                <button type="button" class="btn btn-warning btn-sm"> <i
                    class="icon icon-eraser"></i> Limpiar
                </button>
            </div>
        </div>
    </div>    <!-- end   panel body -->
</div> <!-- end panel default -->
</section>
                   